- name: launch Webserver1 in Metapod
  hosts: local
  vars_files:
    - vars/var.yml

  tasks:

  - name: Create a demo router
    os_router:
     state: present
     name: demo-router
     network: Trial 12 Public Network
     interfaces:
        - priv2
